### ISSUE TITLE
In options menu 

### ISSUE THREAD

**Issue by TamaselStefan** [Ravo92/Patch-2.22-Launcher#12]
Add like a save button maybe bottom right and when you click on save or you did not make any changes this will not appear
![Screenshot 2022-12-17 135434](https://user-images.githubusercontent.com/59843767/208240569-ca74f98c-4dbf-45a5-8cd7-ece357b796c1.png)

**Comment by Ravo92** [comment]
Changed with commit 3595da77c9118a69dfc3f478236b58a0e8a65e5d. Closed~
