### ISSUE TITLE
Make installer an .msi to avoid anti-malware detection

### ISSUE THREAD

**Issue by dginovker** [Ravo92/Patch-2.22-Launcher#16]
https://www.reddit.com/r/bfme/comments/zpz1yg/norton_antiv%C3%ADrus_is_flaging_the_new_launcher_as/

**Comment by Ravo92** [comment]
problem is using Norton antivirus. Inno setup is totally legit and fine.

**Comment by Ravo92** [comment]
Also see this one:
https://www.virustotal.com/gui/file/917f936033b56961288eae07b60b847bd239cd14e69be76f3f8f82601a2e8dbb/summary

**Comment by dginovker** [comment]
Generally .msi's don't get flagged

**Comment by dginovker** [comment]
But if it's green it's green :P

**Comment by Ravo92** [comment]
> Generally .msi's don't get flagged

Why should msi be an exception?
Only because its from microsoft? 
Why isnt every virus using msi then? 😋

**Comment by Ravo92** [comment]
But if you want to make an MSI out of the Inno Setup Script, you're warmly welcome!

**Comment by Ravo92** [comment]
We are using signed binaries for a year now. So this is not an issue anymore. Closed~
