### ISSUE TITLE
Options window for bfme1 is flickering 

### ISSUE THREAD

**Issue by original-codematrix** [Ravo92/Patch-2.22-Launcher#2]
I think the title tells the whole story. When you open the bfme1 options the window is flickering for a short amount of time.

**Comment by Ravo92** [comment]
https://learn.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-reduce-graphics-flicker-with-double-buffering-for-forms-and-controls?view=netframeworkdesktop-4.8

Need to check if Form is already double buffered, if not, we will use it.

**Comment by Ravo92** [comment]
Improved it with commit 595f9ec562803cb8e262ab345c448fca7e62366a


Should be way smoother now.

**Comment by original-codematrix** [comment]
I'll take a look today at it

**Comment by dginovker** [comment]
Haven't seen any other reports of it, seems fixed
