### ISSUE TITLE
Populate "About" section on GH page so 2.22 Launcher can be found from Google search

### ISSUE THREAD

**Issue by dginovker** [Ravo92/Patch-2.22-Launcher#21]
i.e. my fork of Loriborn's shows up on Google, but neither his nor this repo do: https://github.com/dginovker/BFMELauncher

Just steal `BFME Launcher for BFME, BFME 2, ROTWK. Also known as 2.22 Launcher for Battle for Middle Earth I` and add the same tags

**Comment by Ravo92** [comment]
I need more information about this please. What do i need to do?

**Comment by dginovker** [comment]
![image](https://github.com/Ravo92/Patch-2.22-Launcher/assets/32943174/c49ee011-73e8-42b2-875d-02a107e720f4)
This section, where it says "No description, website or topics provided"

**Comment by Ravo92** [comment]
Should be done now. Any Feedback?

**Comment by dginovker** [comment]
Looks good! Google crawlers run every couple weeks so in good time this repo should be at the top of all the search results.
