### ISSUE TITLE
Launcher does not support ARM

### ISSUE THREAD

**Issue by HofmannZ** [Ravo92/Patch-2.22-Launcher#29]
### Expected:
I'd expect to run the launcher and use the Windows built-in x86 emulator.

### Happening:
The app throws an error upon launching the installer:

<img width="451" alt="Screenshot 2023-09-03 at 11 43 59" src="https://github.com/Ravo92/Patch-2.22-Launcher/assets/17142193/77d73217-baaa-4cbd-8a1f-6b964a150f84">

<details>
  <summary>Device specs</summary>
  
  Processor	Apple Silicon   3.20 GHz  (4 processors)
  Installed RAM	16.0 GB
  System type	64-bit operating system, ARM-based processor
</details>

<details>
  <summary>Windows specs</summary>
  
  Edition	Windows 11 Pro
  Version	22H2
  Installed on	‎8/‎6/‎2023
  OS build	22621.2134
  Experience	Windows Feature Experience Pack 1000.22659.1000.0
</details>

**Comment by Ravo92** [comment]
Yes, this is caused by a wrong configured manifest file.

The support enhancement will come with the new GUI (change from winforms to .net maui).

**Comment by Ravo92** [comment]
This is btw. closely related to this issue.

https://github.com/Ravo92/Patch-2.22-Launcher/issues/16

So, when we switch to msi install package, this error should be gone too in theory.

**Comment by HofmannZ** [comment]
@Ravo92 - I am happy to test a prerelease on my machine if that helps

**Comment by Ravo92** [comment]
Hey, please check if the commit 33ac286d62a4c5b3403edc08fd9abcf68d115cb1 changed the behaviour, so you can start the setup on emulated systems.

**Comment by HofmannZ** [comment]
Hey! Release [103](https://github.com/Ravo92/Patch-2.22-Launcher/releases/tag/release-203) Installs on Arm, and the game is playable 🙌

_If the UI is super small, then try to [disable scaling](https://kb.parallels.com/en/123951)_
