### ISSUE TITLE
Add volume adjustment for launcher as option

### ISSUE THREAD

**Issue by original-codematrix** [Ravo92/Patch-2.22-Launcher#3]
Some ppl (me included) have the thing that their main OS volume is kinda loud. There should be a thing to adjust the launcher volume inside the launcher instead of let the ppl open the volume mixer & let them adjust the system volume for the launcher.

**Comment by dginovker** [comment]
This is important for MacOS which doesn't even have a volume mixer :joy:

**Comment by Ravo92** [comment]
They are gone with new GUI. ~Closed
