### ISSUE TITLE
RotWK users who install 2.02 after using 2.22 launcher can't play with RotWK users who install it all by hand 

### ISSUE THREAD

**Issue by dginovker** [Ravo92/Patch-2.22-Launcher#32]
Apparently it's a known problem, but creating an issue for tracking

(Didn't test this myself, someone told me about it)

**Comment by Ravo92** [comment]
The order tells me that this is a patch 2.02 issue then and not a launcher issue.

Im just delivering the game as patch 2.01.

I also wont support 2.02 in any way since we are not allowed to feature it in the first place.

So no action will be done here for now.

**Comment by Ravo92** [comment]
This issue is obsolete and will be solved with the next update anyway ~closed
