### ISSUE TITLE
Feature: an FPS tracker

### ISSUE THREAD

**Issue by luka-11** [Ravo92/Patch-2.22-Launcher#5]
Adding a FPS tracker, with a button in the settings to turn it on and off

**Comment by dginovker** [comment]
Seems kind of feature-creep

**Comment by Ravo92** [comment]
> Seems kind of feature-creep

Thats lukaa from our server and we talked about it. So its okay, but low priority feature.

**Comment by Ravo92** [comment]
Will be added with vulkan soon. ~closed
